name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  use-reusable-workflow:
    uses: sarafogo/pipeline_templates/.github/workflows/reusable_dotnet.yml@main
    with:
      dotnet-version: '8.0.x'
